### ISSUE TITLE
Crashing in release apk

### ISSUE THREAD

**Issue by manjeets12** [Ivshti/react-native-vlc#10]
It was working good in development mode but as soon as I generated the release apk and installed it on my app it get crashed.

configuration I am working with
android 5.1
react-native 0.43.0
react 16.0.0-alpha.6
url I am testing with "rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/mp4:bigbuckbunnyiphone_400.mp4"

I used adb logcat and get following error with other useless stuff
![capture](https://cloud.githubusercontent.com/assets/17762875/25725936/a19fb834-313f-11e7-85f4-ce1cce036db4.PNG)

**Comment by Ivshti** [comment]
Try disabling proguard in your gradle file

**Comment by manjeets12** [comment]
@Ivshti thanks it works, but any specific reason it worked that way (I spent 2 nights searching about this, and solution is that simple)
