### ISSUE TITLE
 Could not resolve all dependencies

### ISSUE THREAD

**Issue by mucasali** [Ivshti/react-native-vlc#14]
Hello @Ivshti 

i have problem when start react-native like this

Could not find com.github.Ivshti:vlc-android-sdk:2.0.3,

I have followed your instructions, but still have problem.
in my app, i use
  "react": "16.0.0-alpha.6",
   "react-native": "0.44.0",

Is there anything I miss for installation???

Thanks,
Mucasali

**Comment by Ivshti** [comment]
Yes, you need to follow the instructions from the README

**Comment by mucasali** [comment]
i have follow your README, i have add the Jitpack source and the local source to my android repositories (android/build.gradle) and link all gradle,.

Which part I missed @Ivshti ??

**Comment by sabbyt** [comment]
@mucasali Have you installed react-native-video? That fixed dependency issues for me

**Comment by mucasali** [comment]
thanks @sabbyt, but i think this lib have not dependecy with react-native-video. I solved this issue by installing npm via this git, not using npm i react-native-vlc, I think this lib and react-native-vlc have different repositories,

CMIIW
